name: Deploy Staging

on:
  workflow_dispatch:
    inputs:
      artifact_run_id:
        description: Artifact Build run ID to deploy, or 'latest'
        required: false
        default: latest
        type: string

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-environment.yml
    secrets: inherit
    with:
      artifact_run_id: ${{ inputs.artifact_run_id }}
      aws_region: ${{ vars.AWS_REGION_STAGING != '' && vars.AWS_REGION_STAGING || 'us-east-1' }}
      aws_role_arn: ${{ vars.AWS_ROLE_ARN_STAGING }}
      environment_name: staging
      environment_path: infra/terraform/environment/staging
